export const ADMINISTRATIVE_RESET_REASON_CODES = [
  "ADMIN_RESET_USER_REQUEST",
  "ADMIN_RESET_ACCESS_RECOVERY",
  "ADMIN_RESET_SECURITY_INCIDENT",
  "ADMIN_RESET_ADMINISTRATIVE_CORRECTION",
] as const

export type AdministrativeResetReasonCode =
  (typeof ADMINISTRATIVE_RESET_REASON_CODES)[number]
